### ISSUE TITLE
INTERNSHIP-DohaElsawy

### ISSUE THREAD

**Issue by dohaelsawy** [codescalersinternships/home#276]
## intro 
This is a rough plan of the development internship program for 2024 -8 to 10 weeks program-. The intern need to be able to reason about the code, and be able to write tests (units and integration), then they should be able to contribute to the daily work with the team.

## Week 0

In this week we spend some time to get familiar with the basics of linux, git, shell, and how to read the documentation

- [ ] https://www.youtube.com/playlist?list=PLyzOVJj3bHQuloKGG59rS43e29ro7I57J ( lect 1-7)
- [ ] Effective Shell: https://effective-shell.com
- [ ] Linux Intro/Essentials https://lym.readthedocs.io/en/latest/ (till Linux Services, package management (apt only), networking commands)
- [ ] Reading manpages of `echo, env, cat, wc, head, tail, yes, true, false, tree`
- [ ] git https://www.atlassian.com/git (branches, commit, log, merge, rebase, tag, github flow)

### extra
- [ ] audit courses https://www.coursera.org/professional-certificates/google-it-support
- [ ] https://ubuntu.com/server/docs

## Week 1

We get our feet with learning the fundamentals of Go, and start developing small utilities in Go.

- [x] Go fundamentals [gobyexample](https://gobyexample.com)
- [x] coreutils https://github.com/codescalersinternships/home/issues/105: `echo, env, cat, wc, head, tail, yes, true, false, tree` (use gobyexample to speed up things)
- [x] build your own git https://leshenko.net/p/ugit/# (5 steps)

## Week 2

We introduce you to the testing, writing unit tests, configuring github workflows.

- [x] [learn Go with tests](https://quii.gitbook.io/learn-go-with-tests/)
- [x] INI Parser project with tests https://github.com/codescalersinternships/home/issues/21 
- [x] Github [Workflows](https://docs.github.com/en/actions/learn-github-actions/understanding-github-actions)
- [x] build your own git https://leshenko.net/p/ugit/# (5 steps)

## Week 3

In this week we develop a small http service and we cover how to test it and how to build a client to consume its api

- [x] Datetime server https://github.com/codescalersinternships/home/issues/144
- [x] HTTP Service testing
- [x] DateTime http client https://github.com/codescalersinternships/home/issues/145
- [ ] [context package](https://medium.com/rungo/understanding-the-context-package-b2e407a9cdae)
- [x] build your own git https://leshenko.net/p/ugit/# (5 steps)

### Extra

- [ ] [go101](https://go101.org/article/101.html)
- [ ] [ultimatego](https://github.com/hoanhan101/ultimate-go)

## Week 4

In this week we get familiar with docker and docker compose, what they do, and how to build a docker image, and how to reduce its size. Then we go through REST API, Swagger, and Postman. and we will build a small client that consumes the pokemon Restful API service. 

- [x] Docker
- [x] Multistaged builds https://fabianlee.org/2020/01/26/golang-using-multi-stage-builds-to-create-clean-docker-images/
- [x] Docker compose
- [x] REST API
- [ ] Swagger
- [ ] Postman
- [x] pokemon API https://pokeapi.co/ (create http client for pokemon API + tests) https://github.com/codescalersinternships/home/issues/146
- [x] build your own git https://leshenko.net/p/ugit/# (5 steps)

### Resources

- [ ] docker docs https://docs.docker.com/engine/install/ubuntu/
- [ ] https://www.youtube.com/watch?v=3c-iBn73dDE
- [ ] https://www.youtube.com/watch?v=pTFZFxd4hOI
- [ ] https://www.youtube.com/watch?v=HG6yIjZapSA
- [ ] https://www.youtube.com/watch?v=PrusdhS2lmo
- [ ] https://www.youtube.com/watch?v=X48VuDVv0do
- [ ] docker docs https://docs.docker.com/engine/install/ubuntu/
- [ ] https://www.youtube.com/watch?v=3c-iBn73dDE
- [ ] https://www.youtube.com/watch?v=pTFZFxd4hOI
- [ ] https://www.youtube.com/watch?v=HG6yIjZapSA
- [ ] https://www.youtube.com/watch?v=PrusdhS2lmo
- [ ] multistaged builds https://fabianlee.org/2020/01/26/golang-using-multi-stage-builds-to-create-clean-docker-images/
- [ ] https://www.youtube.com/watch?v=X48VuDVv0do

## Week 5

Here we introduce you to the concept of MVC.

- [x] Secret Note MVC https://github.com/codescalersinternships/home/issues/153
- [x] build your own git https://leshenko.net/p/ugit/# (5 steps)

## Week 6

In this week we will redo the project as SPA, by providing two services: an API service and a frontend that consumes that API -next week-
- [ ] Secret Note API https://github.com/codescalersinternships/home/issues/152

## Week 7
- [ ] Frontend https://github.com/codescalersinternships/home/issues/152 
- [ ] build your own git https://leshenko.net/p/ugit/# (5 steps)

### Resources

- [ ] Frontend track https://github.com/MohamedElmdary/cat-frontend-circle-road-map
- [ ] https://github.com/MohamedElmdary/frontend-session-resources
- [ ] [Vue.js](https://vuejs.org/)
- [ ] [React Megatutorial](https://blog.miguelgrinberg.com/post/the-react-mega-tutorial-chapter-1-modern-javascript)
- [ ] https://selenium-python.readthedocs.io/locating-elements.html
- [ ] https://www.toolsqa.com/selenium-webdriver/selenium-locators/
- [ ] https://filiphric.com/cypress-basics-selecting-elements
- [ ] Cypress https://testautomationu.applitools.com/advanced-cypress-tutorial/

Testing session: https://docs.google.com/presentation/d/1ljUyCXWN-ZF3FyNDUOYXoyOrEagy_DoXWeL5wDMF47Y/edit?usp=sharing

## Week 8 (onboarding to threefold)
Starting from that week the intern should be able to write testable code and can be introduced to our platform and projects. Best intro the platform by manually testing the capabilities and reporting issues on the normal of the enduser. 

- [ ] Intro to Codescalers and TFGrid Platform
- [ ] How to write a bug report https://www.softwaretestinghelp.com/how-to-write-good-bug-report/
- [ ] Manual Testing 
- [ ] Namespaces, CGroups, Docker
- [ ] The Dashboard and deploying your first machine on the threefold grid)
- [ ] Terraform and deploying your virtual machines machines on the threefold grid)
- [ ] Rust fundamentals
- [ ] Manually Testing the platform (intro to testlodge -qa tool we use to develop and track our tests-)

## Week 9-end of internship week 10 distributed on teams (sdk-go, zos, sdk-ts, sdk-dart)

- [ ] 4 solutions
- [ ] GPU services integration *
- [ ] ZOS service rewrites in rust
- [ ] Freeflow twin
- [ ] Threefold Connect *
- [ ] Planetary Desktop/mobile App
- [ ] Increase code coverage
- [ ] Deployments web builder (drag/drop)
- [ ] IaC
- [ ] heroku like system on the grid maybe? gridify pushing forward

## Extra tasks

- [ ] RESP Parser https://github.com/codescalersinternships/home/issues/275
- [ ] dotenv https://github.com/codescalersinternships/home/issues/208
- [ ] Makego https://github.com/codescalersinternships/home/issues/157
- [ ] Busybox img https://github.com/codescalersinternships/home/issues/103
- [ ] NTP https://github.com/codescalersinternships/home/issues/141
- [ ] BMP Width/Height https://github.com/codescalersinternships/home/issues/142
- [ ] Msgpack https://github.com/codescalersinternships/home/issues/240
- [ ] [bitcask paper](https://github.com/codescalersinternships/home/issues/37)

## Sessions
- [ ] REST API
- [ ] GraphQL
- [ ] Protobuf
- [ ] gRPC
- [ ] Concurrency
- [ ] Blockchain
- [ ] Vue
- [ ] Docker/CGroups
- [ ] Testing
- [ ] Redis
- [ ] UNIX Programming
- [ ] Caddy
- [ ] Zinit
- [ ] Flist
- [ ] Raft
- [ ] Packer
- [ ] Zig
- [ ] TLS
- [ ] Encryption (symmetric/asymmetric)
- [ ] 12 factor apps https://12factor.net
- [ ] Github flow https://docs.github.com/en/get-started/quickstart/github-flow
- [ ] Building a small busybox based distro

## daily work 
- [ ] write your own git: https://leshenko.net/p/ugit/#
- [ ] [creating package in 2022](https://mathspp.com/blog/how-to-create-a-python-package-in-2022)
- [ ] [python](https://docs.python.org/3/tutorial/index.html)
- [ ] [django rest framework DRF](https://www.django-rest-framework.org/)
- [ ] [pymotw](https://pymotw.com/3/) 
- [ ] [jinja](https://jinja.palletsprojects.com/en/2.10.x/)
- [ ] [bottle](https://bottlepy.org/docs/dev/)
- [ ] [exploreflask](https://exploreflask.com/en/latest/)
- [ ] flask megatuorial](https://blog.miguelgrinberg.com/post/the-flask-mega-tutorial-part-i-hello-world)
- [ ] [TDD with python/django](https://www.obeythetestinggoat.com)
- [ ] [redis university](https://university.redis.com)
- [ ] [redis in action](https://redislabs.com/redis-in-action/) is a book that will help you to know redis by practice.
- [ ] The following topics are important to know about Redis:
  - [ ] Data structures
  - [ ] Pub/Sub [Guide link 1](https://redis.io/topics/pubsub) | [Guide link 2](https://www.tutorialspoint.com/redis/redis_pub_sub.htm) | [Video](https://youtu.be/33N1mgiRYK0)
  - [ ] Data persistence (snapshots & AOF) [Guide link](https://redis.io/topics/persistence)  | [Video](https://youtu.be/Hbt56gFj998?t=2042)
  - [ ] Transactions [Guide link](https://www.tutorialspoint.com/redis/redis_transactions.htm)
  - [ ] Distributed locking [Guide link1](https://redis.io/topics/distlock) | [Guide link2](https://medium.com/@rohansaraf/distributed-locking-with-redis-ecb0773e7695)
  - [ ] Resp Protocol [Guide link](https://redis.io/topics/protocol)
### Software development process / testing

- [ ] Trunk based development https://trunkbaseddevelopment.com/

## networking
- [ ] [CCNA/CCNP](https://www.youtube.com/playlist?list=PL77yNtB4-LjnN2FU3h1v5hIJOHZfW9ugq)

## linux 
- [ ] effective shell: https://effective-shell.com
- [ ] [ubuntu server guide](https://help.ubuntu.com/lts/serverguide/)
- [ ] nginx](https://www.nginx.com/)
- [ ] [debian handbook](https://debian-handbook.info)
- [ ] [tmux](https://www.hamvocke.com/blog/a-quick-and-easy-guide-to-tmux/)
- [ ] [building root filesystem](https://emreboy.wordpress.com/2012/12/20/building-a-root-file-system-using-busybox/)
- [ ] [coredns](https://coredns.io)
- [ ] https://www.nginx.com/blog/what-are-namespaces-cgroups-how-do-they-work/ 
- [ ] https://www.youtube.com/watch?v=8fi7uSYlOdc
- [ ] [build container in 500Lines](https://blog.lizzie.io/linux-containers-in-500-loc.html)
- [ ] [unix programming](https://stevens.netmeister.org/631/#syllabus)

## Raft/Distributed systems
- [ ] https://learn.particular.net/courses/distributed-systems-design-fundamentals-online
- [ ] slides: https://thesecretlivesofdata.com/raft/
- [ ] https://raft.github.io
- [ ] https://en.wikipedia.org/wiki/Raft_(algorithm)

## binary serialization
- [ ] https://capnproto.org/
- [ ] https://google.github.io/flatbuffers/
- [ ] https://developers.google.com/protocol-buffers

## Optional:
- [ ] Kubernetes
- [ ] Helm Charts
- [ ] Blockchain (substrate, cosmos, solidity?)

**Comment by dohaelsawy** [comment]
# Yesterday update 28/8/2024
## Studied 
- Effective Shell :
  - [x] transitioning-to-the-shell
  - [x] Core Skills 
- Missing Semester :
  - [x] Lecture 1: Course Overview + The Shell (2020)
- Linux Intro/Essentials :
   - [x] Shell commands

**Comment by dohaelsawy** [comment]
# Update 29/8/2024
## Studied
-  Effective Shell :
      - [x] Manipulating Text and Streams
      - Shell Scripting
          - [x] Shell Script Essentials
  - The Flask Mega-Tutorial :
       - [x] chapter 1 -> Hello World
       - [x] chapter 2 -> Templates

**Comment by dohaelsawy** [comment]
# Update 31/8/24
## Studied : 
* The Flask Mega-Tutorial :
  - [x] Chapter 3: Web Forms
  - [ ] Chapter 4: Database
* Missing Semester :
   - [x] Lecture 4: Data Wrangling (2020)
   - [x] Lecture 3: Editors (vim) (2020)
* Linux Intro/Essentials :
  - [x] Useful commands
* Refresh Python Basics -> classes + packages

**Comment by dohaelsawy** [comment]
# Update 1/9/2024
## studied: 
* modified coreutils functions
* Shell Scripting
   - [x] Variables, Reading Input, and Mathematics
   - [x] Mastering Conditional Logic
   - [x] Loops and working with Files and Folders

**Comment by dohaelsawy** [comment]
# Update 2/9/2024:
## Studied : 
- Software Design by Example 
   - [x] Introduction
   - [x] Objects and Classes
- Implemented 3 steps from DIY git 
- step 4 has error and going to be solved inshallah by @xmonader tomorrow  
- read this article [What is Git Object Model](https://medium.com/mindorks/what-is-git-object-model-6009c271ca66) to make me understand more about step 4 and git object models in general

**Comment by dohaelsawy** [comment]
# Update 3/9/2024:
 - went to the company and discuss several topics
 - studied this video [ccna](https://www.youtube.com/watch?v=THkNC2EJav4&list=PL77yNtB4-LjnN2FU3h1v5hIJOHZfW9ugq&index=2) about cabling and networks type

**Comment by dohaelsawy** [comment]
# Update 4/9/2024:
### code : 
- updated coreutils project structure and apply some notes
- made a github action flow to build go and linter 
### after work hours : 
- tried to make a release using github actions but it didn't work
- applied the 5th step in DIY git in python
- watched [ccna] (https://www.youtube.com/watch?v=60pndg7PiXY&list=PL77yNtB4-LjnN2FU3h1v5hIJOHZfW9ugq&index=3&t=31s) about Encor..CCNA 200-301 and Encor..UTP cable

**Comment by dohaelsawy** [comment]
# Update 11/9/2024:
### code : 
- INI project : 
-  fix bugs, 
- add some tests, 
- make testing workflows 
### study:
- study 5 steps of DIY git 
- watched a visualization tutorial about raft

**Comment by dohaelsawy** [comment]
# Update 8/9/24 : 
- learn about INI files in general and explore source code of [INI go package](https://ini.unknwon.io/docs/intro/getting_started)
- switch my environment from widows to linux successfully
- implement a initial version of LoadFromFile & LoadFromString functions in INI project #21

**Comment by dohaelsawy** [comment]
# Update 9/9/24:
- review test with bible to refresh some concepts 
### project #21 
- implement the rest of functionality 
- basic test case for each function 
- update LoadFromString function logic

**Comment by dohaelsawy** [comment]
# Update 10/9/24:
### project #21 
- delete all previous test cases and start over with more detailed ones 
- fix bugs and more refactor 
- make build workflow without testing flow

**Comment by dohaelsawy** [comment]
# Update 11/9/24:
### project #21 
- make readme file for user document 
- make code documentation
- more refactoring 
- make workflow for testing 
### study
- watch visualization tutorial about [raft](https://thesecretlivesofdata.com/raft/)
- make more 5 steps at DIYgit

**Comment by dohaelsawy** [comment]
# Update 12/9/24:
### study
- [Flask Web Development Developing](https://coddyschool.com/upload/Flask_Web_Development_Developing.pdf) finish chapter 4 : web forms 
- [Distributed Systems Design Fundamentals](https://learn.particular.net/courses/take/distributed-systems-design-fundamentals-online/) till fallacy 3 bandwidth isn't a problem

**Comment by dohaelsawy** [comment]
# Update 15/9/24:
### Project #284 : 
- [x] implement server date time using gin and http 
- [x] make makefile for linter, format and build binaries 
- [x] test cases for each server
### after work inshallah : 
- project
   - [ ] docker file for each server
   - [ ] docker compose 
   - [x] docs in code and readme file 
- study 
   - [ ] Certified Kubernetes Application Developer (CKAD) till core concepts

**Comment by dohaelsawy** [comment]
# Update 16/9/24:
### Project #284 :  
   - [x] docker file for each server
   - [x] docker compose 
   - [x] docs in code and readme file 
- study 
   - [x] Certified Kubernetes Application Developer (CKAD) till core concepts
- know how zos works -hope to know more internals-

**Comment by dohaelsawy** [comment]
# Update 17/9/24:
### Project #286   :  
   - [x] implement client functionality 
   - [x] test client functions 
### study 
   - [x] Certified Kubernetes Application Developer (CKAD) laps in core concept section 
 ### after work inshallah :
 - [ ] Certified Kubernetes Application Developer (CKAD) till secrets in configuration part 
 - [x]  finish datatime client project functions 
 - [x] test rest of functionality 
 - [ ] implement Retry Mechanism

**Comment by dohaelsawy** [comment]
# Update 18/9/24:
### Project #286   :  
   - [x] implement retry mechanism using backoff
   - [x] refactor code 
   - [x] implement logging system
   - [x] make read me file
 ### after work inshallah :
 - [ ] apply coding comments on ini parser  
 - [ ]  make code document in datatime client project

**Comment by dohaelsawy** [comment]
# Update 19/9/24: 
   - [x] apply coding review comments on ini parser
   - [x] refactor http Client project and applied what i learnt from ini review 
   - [x] refactor  server project and applied what i learnt from ini review
 ### after work inshallah :
 - [x]  Certified Kubernetes Application Developer (CKAD) till secrets in configuration part
 - [ ]  weekly 5 steps from DIY git

**Comment by dohaelsawy** [comment]
# Update 21/9/24: 
 - [x]  Certified Kubernetes Application Developer (CKAD) finish configuration part
 - [x]  weekly 5 steps from DIY git

**Comment by dohaelsawy** [comment]
# Update 22/9/24: 
   - [x] done client function and tests 
   - [x] initial version from resource api 
 ### after work inshallah :
 - [ ] finish resource api
 - [ ] make tests for resource api
 - [ ] study kubernetes multiple containers sections 
 - [x] refresh technology part 1 in kloudkode aws course

**Comment by dohaelsawy** [comment]
# Update 23/9/24: 
### project #294 
 - [x] finish resource api
 - [x] make tests for resource api
 - [x] make pokemon api and its test
 ### after work inshallah :
 - [x] chapter 3 from system design

**Comment by dohaelsawy** [comment]
# Update 24/9/24: 
 - [x] chapter 4 , 5 from system design 
 - [x] sessions at office

**Comment by dohaelsawy** [comment]
# Update 25/9/24: 
### project #299 
 - [x] start the project and some initial structure 
### session
- [x] prepare concurrency session content 
- [x] meeting with esalm to discuss the session content

**Comment by dohaelsawy** [comment]
## Update 26/9/24: 
### project #299 
 - [x] implement cpu functions with its test
 - [x] refactor the code to be more abstracted
 - [x] implement mocking for loading file 
### session
- [x] prepare concurrency session examples and exercises
### study 
- [x] study this tutorial about [dependency injection](https://www.youtube.com/watch?v=HrBd63AWbBg)

**Comment by dohaelsawy** [comment]
## update 29/9/24
### project #299 
 - [x] implement proc functions with test in DI
 - [x] refactor cpu code to be following DI
 - [x] refactor memory code to be following DI
### else
- [x] git 2 steps from previous week :"}
- [ ] refactor client code server

**Comment by dohaelsawy** [comment]
### update 30/9/24:
- [x] refactor client server based on code review
- [x] finish 5 ugit steps for previous week 
- [x] watched deploying tutorial for [k8s](https://www.youtube.com/watch?v=XltFOyGanYE)
- [x] pass aws exam yahhooo alhamdulallah  :}

**Comment by dohaelsawy** [comment]
### update 1/10/24:
- [x] deploy datetime each server on Kubernetes
- [x] apply namespaces and services 
- [x] apply ingress but still waiting for DNS server to be approved from cloudflare

**Comment by dohaelsawy** [comment]
### update 2/10/24:
- [x] apply ingress controller and solve some issues but will try different approach
- [x] apply helm and templates and values *still working on it*
- [x] watch helm tutorials for better visualization

**Comment by dohaelsawy** [comment]
### update 3/10/24
- [x] read template chapter in system design 
- [x] read first chapter in orchestrater in golang 
- [x] done 5 DIY git steps for this week 
- [x] done 50% of session presentation

**Comment by dohaelsawy** [comment]
### update 6/10/24:
- [x] read chapter 2 from orchestrate in golang
- [x] done 5 DIY git steps for this week
- [x] %80 of session presentation :"
#### late update
- [x] finished session presentation xD

**Comment by dohaelsawy** [comment]
### update 7/10/24:
#### project #303 
- [x] add initial implementation for create note
- [x] reviewed django documentation 
- [x] learn how to test in django 
#### session:
- [x] apply eslam's comments on session presentation

**Comment by dohaelsawy** [comment]
# update 8/10/24:
 #### project #303
- [x] finish create and retrieve note functions
- [x] implement tests for both functions
- [x] read test official tutorial in django documentation
- [x] read [mdn test tutoria](https://developer.mozilla.org/en-US/docs/Learn/Server-side/Django/Testing)
- [x] try to make request limit but didn't work :}

**Comment by dohaelsawy** [comment]
### update 9/10/24:
#### project #303 
- [x] add rate limit implementation
- [x] finish tests 
- [x] convert code from httpresponse to render to implement templates

**Comment by dohaelsawy** [comment]
### update 10/10/24:
#### project #303 
- [x] finish templates design and linking 
- [x] implement auth system
- [x] learning Selenium from this [course](https://www.youtube.com/watch?v=j7VZsCCnptM&t=382s)

**Comment by dohaelsawy** [comment]
### update 13/10/24:
#### project #303 
- [x] solved firfox webdriver issue, alhamdullah take my foraver 
- [x] make 3 of flows for selenium tests
#### others
- [x] made my concurrency session, yaahhh XD

**Comment by dohaelsawy** [comment]
### update 14/10/24:
#### project #303 
- [x] complete selenium flow
- [x] make docker and docker-compose
- [x] solved issue in linking between my app and container 
#### others
- [x]  done 5 DIY git steps for this week

#### super late update:
#303  
- [x] solved memcached problem for ratelimit property
- [x] solved volume issue, was not listening

**Comment by dohaelsawy** [comment]
#### update 15/10/24:
#303
- [x] fixed  clear cache test issue 
- [x] make read me file 
#### others
- [x] watch [vue tutorial](https://www.youtube.com/watch?v=bzlFvd0b65c)

**Comment by dohaelsawy** [comment]
update 16/10/14:
- [x] study several of tutorial/articles about concurrency patterns and prepare the content 
- [x] put all things together in presentation, isa will send a copy for eslam's review :}

**Comment by dohaelsawy** [comment]
### update 17/10/24:
- [x] study standard layout for go web app
- [x] study view crash course 
- [x] git 5 steps

**Comment by dohaelsawy** [comment]
### update 20/10/24:
#310 
- [x] connect to db -didn't work-
- [x] create docker-compose and docker file 
- [x] create user model and basic functions

**Comment by dohaelsawy** [comment]
### update 21/10/24:
#310 
- [x] connect to db -worked yyyaaaahhh-
- [x]  add setup for hot reload inside container 
- [x] initial jwt implementation for login, registration

**Comment by dohaelsawy** [comment]
### update 22/10/24:
#310 
- [x] middleware 
- [x]  link queries for db
- [x] token handling via header and then change it to cookies

**Comment by dohaelsawy** [comment]
### update 23/10/24:
#310 
- [x] fixed errors, validation, a lot of refactoring :}
- [x]  inject db 
- [x] account crud

**Comment by dohaelsawy** [comment]
### update 24/10/24:
#310 
- [x] test for db queries, controllers, middleware, anything

**Comment by dohaelsawy** [comment]
### update 25/10/24:
#310 
- [x] analytics apis and its test 
- [x] modified any errors and upload photos for user and its test

**Comment by dohaelsawy** [comment]
### update 26/10/24:
#310 
- [x] swagger docs
- [x]  vue login, tutorials
