### ISSUE TITLE
INTERNSHIP-Fatma Ebrahim

### ISSUE THREAD

**Issue by fatmaebrahim** [codescalersinternships/home#282]
## intro 
This is a rough plan of the development internship program for 2024 -8 to 10 weeks program-. The intern need to be able to reason about the code, and be able to write tests (units and integration), then they should be able to contribute to the daily work with the team.

## Week 0

In this week we spend some time to get familiar with the basics of linux, git, shell, and how to read the documentation

- [ ] https://www.youtube.com/playlist?list=PLyzOVJj3bHQuloKGG59rS43e29ro7I57J ( lect 1-7)
- [x] Effective Shell: https://effective-shell.com
- [ ] Linux Intro/Essentials https://lym.readthedocs.io/en/latest/ (till Linux Services, package management (apt only), networking commands)
- [ ] Reading manpages of `echo, env, cat, wc, head, tail, yes, true, false, tree`
- [x] git https://www.atlassian.com/git (branches, commit, log, merge, rebase, tag, github flow)

### extra
- [ ] audit courses https://www.coursera.org/professional-certificates/google-it-support
- [ ] https://ubuntu.com/server/docs

## Week 1

We get our feet with learning the fundamentals of Go, and start developing small utilities in Go.

- [x] Go fundamentals [gobyexample](https://gobyexample.com)
- [x] coreutils https://github.com/codescalersinternships/home/issues/105: `echo, env, cat, wc, head, tail, yes, true, false, tree` (use gobyexample to speed up things)
- [x] build your own git https://leshenko.net/p/ugit/# (5 steps)

## Week 2

We introduce you to the testing, writing unit tests, configuring github workflows.

- [x] [learn Go with tests](https://quii.gitbook.io/learn-go-with-tests/)
- [x] INI Parser project with tests https://github.com/codescalersinternships/home/issues/21 
- [x] Github [Workflows](https://docs.github.com/en/actions/learn-github-actions/understanding-github-actions)
- [x] build your own git https://leshenko.net/p/ugit/# (5 steps)

## Week 3

In this week we develop a small http service and we cover how to test it and how to build a client to consume its api

- [x] Datetime server https://github.com/codescalersinternships/home/issues/144
- [x] HTTP Service testing
- [x] DateTime http client https://github.com/codescalersinternships/home/issues/145
- [ ] [context package](https://medium.com/rungo/understanding-the-context-package-b2e407a9cdae)
- [x] build your own git https://leshenko.net/p/ugit/# (5 steps)

### Extra

- [ ] [go101](https://go101.org/article/101.html)
- [ ] [ultimatego](https://github.com/hoanhan101/ultimate-go)

## Week 4

In this week we get familiar with docker and docker compose, what they do, and how to build a docker image, and how to reduce its size. Then we go through REST API, Swagger, and Postman. and we will build a small client that consumes the pokemon Restful API service. 

- [x] Docker
- [x] Multistaged builds https://fabianlee.org/2020/01/26/golang-using-multi-stage-builds-to-create-clean-docker-images/
- [x] Docker compose
- [x] REST API
- [x] Swagger
- [x] Postman
- [x] pokemon API https://pokeapi.co/ (create http client for pokemon API + tests) https://github.com/codescalersinternships/home/issues/146
- [x] build your own git https://leshenko.net/p/ugit/# (5 steps)

### Resources

-  docker docs https://docs.docker.com/engine/install/ubuntu/
-  https://www.youtube.com/watch?v=3c-iBn73dDE
-  https://www.youtube.com/watch?v=pTFZFxd4hOI
-  https://www.youtube.com/watch?v=HG6yIjZapSA
-  https://www.youtube.com/watch?v=PrusdhS2lmo
-  https://www.youtube.com/watch?v=X48VuDVv0do
-  docker docs https://docs.docker.com/engine/install/ubuntu/
-  https://www.youtube.com/watch?v=3c-iBn73dDE
-  https://www.youtube.com/watch?v=pTFZFxd4hOI
-  https://www.youtube.com/watch?v=HG6yIjZapSA
-  https://www.youtube.com/watch?v=PrusdhS2lmo
-  multistaged builds https://fabianlee.org/2020/01/26/golang-using-multi-stage-builds-to-create-clean-docker-images/
-  https://www.youtube.com/watch?v=X48VuDVv0do

## Week 5

Here we introduce you to the concept of MVC.

- [x] Secret Note MVC https://github.com/codescalersinternships/home/issues/153
- [x] build your own git https://leshenko.net/p/ugit/# (5 steps)

## Week 6

In this week we will redo the project as SPA, by providing two services: an API service and a frontend that consumes that API -next week-
- [ ] Secret Note API https://github.com/codescalersinternships/home/issues/152

## Week 7
- [ ] Frontend https://github.com/codescalersinternships/home/issues/152 
- [ ] build your own git https://leshenko.net/p/ugit/# (5 steps)

### Resources

-  Frontend track https://github.com/MohamedElmdary/cat-frontend-circle-road-map
-  https://github.com/MohamedElmdary/frontend-session-resources
-  [Vue.js](https://vuejs.org/)
-  [React Megatutorial](https://blog.miguelgrinberg.com/post/the-react-mega-tutorial-chapter-1-modern-javascript)
-  https://selenium-python.readthedocs.io/locating-elements.html
-  https://www.toolsqa.com/selenium-webdriver/selenium-locators/
-  https://filiphric.com/cypress-basics-selecting-elements
-  Cypress https://testautomationu.applitools.com/advanced-cypress-tutorial/

Testing session: https://docs.google.com/presentation/d/1ljUyCXWN-ZF3FyNDUOYXoyOrEagy_DoXWeL5wDMF47Y/edit?usp=sharing

## Week 8 (onboarding to threefold)
Starting from that week the intern should be able to write testable code and can be introduced to our platform and projects. Best intro the platform by manually testing the capabilities and reporting issues on the normal of the enduser. 

- [ ] Intro to Codescalers and TFGrid Platform
- [ ] How to write a bug report https://www.softwaretestinghelp.com/how-to-write-good-bug-report/
- [ ] Manual Testing 
- [ ] Namespaces, CGroups, Docker
- [ ] The Dashboard and deploying your first machine on the threefold grid)
- [ ] Terraform and deploying your virtual machines machines on the threefold grid)
- [ ] Rust fundamentals
- [ ] Manually Testing the platform (intro to testlodge -qa tool we use to develop and track our tests-)

## Week 9-end of internship week 10 distributed on teams (sdk-go, zos, sdk-ts, sdk-dart)

- [ ] 4 solutions
- [ ] GPU services integration *
- [ ] ZOS service rewrites in rust
- [ ] Freeflow twin
- [ ] Threefold Connect *
- [ ] Planetary Desktop/mobile App
- [ ] Increase code coverage
- [ ] Deployments web builder (drag/drop)
- [ ] IaC
- [ ] heroku like system on the grid maybe? gridify pushing forward

## Extra tasks

- [ ] RESP Parser https://github.com/codescalersinternships/home/issues/275
- [ ] dotenv https://github.com/codescalersinternships/home/issues/208
- [ ] Makego https://github.com/codescalersinternships/home/issues/157
- [ ] Busybox img https://github.com/codescalersinternships/home/issues/103
- [ ] NTP https://github.com/codescalersinternships/home/issues/141
- [ ] BMP Width/Height https://github.com/codescalersinternships/home/issues/142
- [ ] Msgpack https://github.com/codescalersinternships/home/issues/240
- [ ] [bitcask paper](https://github.com/codescalersinternships/home/issues/37)

## Sessions
- [ ] REST API
- [ ] GraphQL
- [ ] Protobuf
- [ ] gRPC
- [ ] Concurrency
- [ ] Blockchain
- [ ] Vue
- [ ] Docker/CGroups
- [ ] Testing
- [ ] Redis
- [ ] UNIX Programming
- [ ] Caddy
- [ ] Zinit
- [ ] Flist
- [ ] Raft
- [ ] Packer
- [ ] Zig
- [ ] TLS
- [ ] Encryption (symmetric/asymmetric)
- [ ] 12 factor apps https://12factor.net
- [ ] Github flow https://docs.github.com/en/get-started/quickstart/github-flow
- [ ] Building a small busybox based distro

## daily work 
- [ ] write your own git: https://leshenko.net/p/ugit/#
- [ ] [creating package in 2022](https://mathspp.com/blog/how-to-create-a-python-package-in-2022)
- [ ] [python](https://docs.python.org/3/tutorial/index.html)
- [ ] [django rest framework DRF](https://www.django-rest-framework.org/)
- [ ] [pymotw](https://pymotw.com/3/) 
- [ ] [jinja](https://jinja.palletsprojects.com/en/2.10.x/)
- [ ] [bottle](https://bottlepy.org/docs/dev/)
- [ ] [exploreflask](https://exploreflask.com/en/latest/)
- [ ] [flask megatuorial](https://blog.miguelgrinberg.com/post/the-flask-mega-tutorial-part-i-hello-world)
- [ ] [TDD with python/django](https://www.obeythetestinggoat.com)
- [ ] [redis university](https://university.redis.com)
- [ ] [redis in action](https://redislabs.com/redis-in-action/) is a book that will help you to know redis by practice.
- [ ] The following topics are important to know about Redis:
  - [ ] Data structures
  - [ ] Pub/Sub [Guide link 1](https://redis.io/topics/pubsub) | [Guide link 2](https://www.tutorialspoint.com/redis/redis_pub_sub.htm) | [Video](https://youtu.be/33N1mgiRYK0)
  - [ ] Data persistence (snapshots & AOF) [Guide link](https://redis.io/topics/persistence)  | [Video](https://youtu.be/Hbt56gFj998?t=2042)
  - [ ] Transactions [Guide link](https://www.tutorialspoint.com/redis/redis_transactions.htm)
  - [ ] Distributed locking [Guide link1](https://redis.io/topics/distlock) | [Guide link2](https://medium.com/@rohansaraf/distributed-locking-with-redis-ecb0773e7695)
  - [ ] Resp Protocol [Guide link](https://redis.io/topics/protocol)
### Software development process / testing

- [ ] Trunk based development https://trunkbaseddevelopment.com/

## networking
- [ ] [CCNA/CCNP](https://www.youtube.com/playlist?list=PL77yNtB4-LjnN2FU3h1v5hIJOHZfW9ugq)

## linux 
- [ ] effective shell: https://effective-shell.com
- [ ] [ubuntu server guide](https://help.ubuntu.com/lts/serverguide/)
- [ ] [nginx](https://www.nginx.com/)
- [ ] [debian handbook](https://debian-handbook.info)
- [ ] [tmux](https://www.hamvocke.com/blog/a-quick-and-easy-guide-to-tmux/)
- [ ] [building root filesystem](https://emreboy.wordpress.com/2012/12/20/building-a-root-file-system-using-busybox/)
- [ ] [coredns](https://coredns.io)
- [ ] https://www.nginx.com/blog/what-are-namespaces-cgroups-how-do-they-work/ 
- [ ] https://www.youtube.com/watch?v=8fi7uSYlOdc
- [ ] [build container in 500Lines](https://blog.lizzie.io/linux-containers-in-500-loc.html)
- [ ] [unix programming](https://stevens.netmeister.org/631/#syllabus)

## Raft/Distributed systems
- [ ] https://learn.particular.net/courses/distributed-systems-design-fundamentals-online
- [ ] slides: https://thesecretlivesofdata.com/raft/
- [ ] https://raft.github.io
- [ ] https://en.wikipedia.org/wiki/Raft_(algorithm)

## binary serialization
- [ ] https://capnproto.org/
- [ ] https://google.github.io/flatbuffers/
- [ ] https://developers.google.com/protocol-buffers

## Optional:
- [ ] Kubernetes
- [ ] Helm Charts
- [ ] Blockchain (substrate, cosmos, solidity?)

**Comment by fatmaebrahim** [comment]
### 09-09-2024

- Completed rest of coreutils task
- Added golangci-lint to the coreutils repository
- Learned about Github workflows and how to use them in a repository

**Comment by fatmaebrahim** [comment]
### 10-09-2024

- Restructured the coreutils repository
- Learned about git (branches, commit, log, merge, rebase, tag, github flow)
- Read the first part of effective shell

**Comment by fatmaebrahim** [comment]
### 11-09-2024

- Applied the review comments on coreutils task
- Tried to use goreleaser but faced an error with token

**Comment by fatmaebrahim** [comment]
### 12-09-2024

- Applied the review comments version 2 on coreutils task 
- Added release.yml to the coreutils repository
- Learned about Dependency Injection and Mocking in go with tests

**Comment by fatmaebrahim** [comment]
### 16-09-2024

- Added the tests to the iniparser task
- Added test.yml to the iniparser repository
- Learned about HTTP server from go with tests
- Implemented an initial version of datetime server task

**Comment by fatmaebrahim** [comment]
### 17-09-2024

- Learned about docker from docker associate track, finished 10%
- Implemented an initial version of datetime client task

**Comment by fatmaebrahim** [comment]
### 18-09-2024

- Refactored the datetime server repository 
- Added tests for different content types
- Added gin framework to datetime server
- Refactored the datetime client repository

**Comment by fatmaebrahim** [comment]
### 19-09-2024

- Refactored the datetime client repository 
- Added tests to the datetime client
- Added the retry mechanism to the datetime client
-  Added godoc-style comments and README.md to the datetime client

**Comment by fatmaebrahim** [comment]
### 22-09-2024

- Learned about Swagger & Postman
- Implemented the first 3 APIs in Pokemon API task

**Comment by fatmaebrahim** [comment]
### 23-09-2024

- Learned about Rest API
- Implemented GetPokemon and GetResources functions  in Pokemon API task 
-  Added unit tests and test.yml workflow to Pokemon API repository
- Finished 10 steps of build your own git
- Applied the review comments for the iniparser task

**Comment by fatmaebrahim** [comment]
### 24-09-2024

- Read chp1,2,3 from software design by example
- Implemented an initial version of psutil task

**Comment by fatmaebrahim** [comment]
### 25-09-2024

- Finished psutil task
- Started Preparation for Vue Session in 30 mins (will continue blel inshallah :) )

**Comment by fatmaebrahim** [comment]
### 26-09-2024

- Prepared material for Vue session

**Comment by fatmaebrahim** [comment]
### 29-09-2024

- Learned about Kubernetes architecture & components

**Comment by fatmaebrahim** [comment]
### 30-09-2024

- Added config files for Kubernetes to the datetime server
- Used minikube to run the clusters

**Comment by fatmaebrahim** [comment]
### 01-10-2024

- Applied the review comments for the datetime server
- Used the provided clusters to run datetime server deployments

**Comment by fatmaebrahim** [comment]
### 02-10-2024

- Learned about Helm charts
- Packaged datetime server in a Helm Chart
-  Applied the review comments for the datetime client

**Comment by fatmaebrahim** [comment]
### 03-10-2024

- Finished 5 steps of build your own git
- Checked clean code and dependency injection topics

**Comment by fatmaebrahim** [comment]
### 07-10-2024

- Read Django docs tutorial till part 4
- Implemented an initial version of secret note task

**Comment by fatmaebrahim** [comment]
### 08-10-2024

- Read Django docs tutorial till part 4,5
- Handled self-destructing feature of secret note task

**Comment by fatmaebrahim** [comment]
### 11-10-2024

- Added rate limiting to secret note task
- Added authentication to secret note task

**Comment by fatmaebrahim** [comment]
### 14-10-2024

- Added styles to secret note task
- Read Django docs tutorial part 5,6
- Added Django tests to secret note task
- Watched a tutorial for selenium & prepared the setup

**Comment by fatmaebrahim** [comment]
### 16-10-2024

- Added selenium tests to secret note task
- Added docker file and docker compose to secret note task
- Added test.yml workflow to secret note task

**Comment by fatmaebrahim** [comment]
### 20-10-2024

- Read tutorial about gin to memorize it
- Explored The real linktree app
- Created initial version of gin server

**Comment by fatmaebrahim** [comment]
### 21-10-2024

- Watched MongoDB tutorial to memorize it
- Created Most of the user APIs of the linktree app

**Comment by fatmaebrahim** [comment]
### 22-10-2024

- Added JWT authentication for linktree app 
- Restructured the repository into models, database and main

**Comment by fatmaebrahim** [comment]
### 23-10-2024

- Containerized the database for the linktree app
- Added unit tests for signup & login using testify

**Comment by fatmaebrahim** [comment]
### 24-10-2024

- Added unit tests for all  linktree APIs using testify

**Comment by fatmaebrahim** [comment]
### 27-10-2024

- Added Vue app to linktree repository
- Watched a tutorial about Composition API in Vue
- Added navigation structure and templates to Vue app

**Comment by fatmaebrahim** [comment]
### 28-10-2024

- Added styles to Homepage, Login, Signup, Details and Tree views

**Comment by fatmaebrahim** [comment]
### 29-10-2024

- Added scripts to Login and Signup views in Vue app

**Comment by fatmaebrahim** [comment]
### 31-10-2024

- Added scripts to details and tree views in Vue app
- Added visits count API in backend and tested it.
