### ISSUE TITLE
Todo Project - Template

### ISSUE THREAD

**Issue by xmonader** [codescalersinternships/home#40]
need to finish #39 first

- [ ] create a frontend using svelte / typescript - you can learn from https://todomvc.com examples -
- [ ] prepare docker image
- [ ] frontend testing
  - [ ] cypress 
- [ ] setup github actions
- [ ] docker compose
- [ ] docker compose the todo backend and the frontend
