### ISSUE TITLE
Todo API Server - Philo

### ISSUE THREAD

**Issue by PhiloAmgad** [codescalersinternships/home#48]
- [ ] Starting from Swagger https://swagger.io/
- [ ] Prepare the API documentation
- [ ] Create a RESTful server
- [ ] Prepare the docker image https://www.youtube.com/watch?v=3c-iBn73dDE
- [ ] Provide postman or insomnia collections for testing
- [ ] Create API tests
- [ ] setup GitHub actions for testing
- [ ]setup GitHub actions for publishing docker images
