### ISSUE TITLE
Todo API Server - kassem

### ISSUE THREAD

**Issue by 0oM4R** [codescalersinternships/home#49]
- [x]  Starting from Swagger https://swagger.io/
- [x]     Prepare the API [documentation](https://github.com/codescalersinternships/kassem-ToDo/blob/omarTest/todo_swagger.yaml)
- [x]     Create a RESTful server
- [ ]     Prepare the docker image https://www.youtube.com/watch?v=3c-iBn73dDE
- [ ]     Provide postman or insomnia collections for testing
- [ ]     Create API tests
- [ ]     setup GitHub actions https://www.youtube.com/watch?v=R8_veQiYBjI
- [ ]         for testing
- [ ]         for publishing docker images
- [ ]
