### ISSUE TITLE
TODO API Server-doaasaber

### ISSUE THREAD

**Issue by doaasaber** [codescalersinternships/home#50]
- [ ] Starting from Swagger https://swagger.io/
- [ ] Prepare the API documentation
- [ ] Create a RESTful server
- [ ] Prepare the docker image 
- [ ] Provide postman or insomnia collections for testing
- [ ] Create API tests
- [ ] setup GitHub actions 
- [ ] for testing
- [ ] for publishing docker images
