### ISSUE TITLE
Todo API Server - ahmedsalahucf10

### ISSUE THREAD

**Issue by ahmed-salah-ucf** [codescalersinternships/home#52]
- [ ] Starting from Swagger https://swagger.io/
- [ ] Prepare the API documentation
- [ ] Create a RESTful server
- [ ] Prepare the docker image https://www.youtube.com/watch?v=3c-iBn73dDE
- [ ] Provide postman or 
- [ ] insomnia collections for testing
- [ ] Create API tests
- [ ] setup GitHub actions https://www.youtube.com/watch?v=R8_veQiYBjI
  - for testing
  - for publishing docker images
